version: '3'
services:
  code-server-pwa:
    container_name: code-server-pwa
    image: code-server-pwa
    build: .
    ports:
      - "8080:80"
    environment:
      - CODE_SERVER_URL=https://code-server.capybara-shilling.ts.net
    restart: unless-stopped
